 # Python Fundamentals
 &copy; QuantSprout

### iPython Notebook Magic

#### Short cut keys:

-  view shortcut menu - esc then h
-  comment out a line of code = command + /
-  run block of code = shift + enter
-  autocomplete text = tab
-  help for function = shift + tab

#### Web based viewer for ipython notebooks
http://nbviewer.ipython.org/

In [ ]:
### Write your first python code

In [3]:
print("'Hello '")
print("Vasanth")
a=10
b=20
print(a+b)
type(a+b)


'Hello '
Vasanth
30


int

### Numbers in python:

Numeric types: ***int, float,*** and ***bool***.

In [8]:
9/10

0.9

In [12]:
type('True')

str

In [39]:
str.join("apple","fr")

'fappler'

In [22]:
print(str.islower("APPLE"))
str.islower("apple")

False


True

### Methods for Objects
Convert string to lower case

In [25]:
print("vasanth".upper())
"KUMAR".lower()

VASANTH


'kumar'


Basic string insertions

In [29]:
"My name is {}".format('Vasanth')
name = 'Vasanth'
"Where in the world is {}".format(name)

'Where in the world is Vasanth'

In [1]:
print("Vasanth")

Vasanth


You can insert multiple values into strings but requires labels

In [36]:
place = "SF"
"{0} is in {1}".format(name,place)


'Vasanth is in SF'

Try reversing order of the variables name and place.|

### Basic math in python
Some operators are pretty obvious

In [44]:
10 %3 #modulo
10**2
1E3 + 1E-3

1000.001

10 **2


But some operators are less intuitive

In [5]:
a=30000090
b=20
c=a+b
print(c)

30000110


In [8]:
v=49/9
a=4*9
n=195/5
s=6*48
h=36/4
i=9*56
k=295/5
g=v+a+n+s+h+i+k
print(g)


940.4444444444445


In [1]:
def strs_to_floats(list_of_strs, remove_chars=['$',',']):    
    float_list = []                                   
    for string in list_of_strs:
        for char in remove_chars:
            string = string.replace(char, '')
        float_list.append(float(string))
    return float_list

In [5]:
strs_to_floats(['€1,244'],remove_chars=['€',',','$'])

[1244.0]

Assign values to variables

In [45]:
x = 10
y = 5
z = 4

Use math with variables 

In [46]:
x-y

5

In [49]:
x/4

2.5

In [69]:
round(22/7,2)

3.14

Try dividing x by 4.0

### Functions

#### Syntax requires 4 things:
-  prefix of 'def'
-  name for function
-  parentheses followed by a colon
-  indented code on the next line

Create a simple function

In [64]:
def simplest_function():
    print("I made a function")

def square(x):
    return x**2

Call function by name

In [65]:
simplest_function()
square(5)

I made a function


25

You can create a function that requires an input and returns a result

### Line Continuation

Python recognizes that code lines that end with a comma are incomplete

In [66]:
numbers = [1,2,3,
          4,5,6,
          7,8,9]
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


You can also use the backslash

In [68]:
long_string = 'This is a really, really, really'\
+ 'long sentence'
print(long_string)
print("apple")

This is a really, really, reallylong sentence
apple


### Exercise: Build a Function
#### 1. Create a function that converts Celsius to Fahrenheit.  Results should be accurate to at least one decimal point.

In [90]:
def temp_conversion(temp):
    if (type(temp) == float) | (type(temp) == int):
        return temp*1.8 + 32
    else:
        return False
    


#### 2. Update your function to return a sentence (string type) with the Celsius and Fahrenheit values inserted into the string. 

In [104]:
c = "Bananna"

if temp_conversion(c)!= False:
    print("{0} degrees c = {1} degrees F".format(c,temp_conversion(c)))
else:
    print("{0} is not a number and is of type {1}".format(c,type(c)))


Bananna is not a number and is of type <class 'str'>


In [15]:
m = True
n = False
print(m and n) 

False


In [16]:
z="AAAAAaaaaaaaakkakakakakkkakakakakakak"
print(len(z))

37


In [6]:
2018 % 400

18

In [7]:
2018/400

5.045

In [8]:
2020/400

5.05

In [9]:
2020%400

20

In [10]:
2020 // 400

5

In [11]:
18/400


0.045

In [12]:
400 * 5


2000

In [13]:
def is_leap(n):
    if n % 4 == 0:
        if n % 100 == 0:
            if n % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False

In [16]:
is_leap(2020)

True

In [30]:
def calc_default_add(x, y, op='add'):
    if op == 'add':
        return x + y
    elif op == 'sub':
        return x - y
    elif (op != 'add' and op !='sub'):
        return "Valid operation: add, sub"
    return x + y

In [33]:
calc_default_add(6,3)

9

In [38]:
class Person(object):

    def __init__(self, age=20, gender='male', friends=None):
        self.age = age
        self.gender = gender
        if friends is None:
            friends = []
        self.friends = friends

    def print_stats(self):
        print('Age:', self.age)
        print('Gender:', self.gender)

In [39]:
dan = Person()

In [40]:
dan.print_stats()

Age: 20
Gender: male


In [41]:
dan.age = 30

In [43]:
dan.print_stats()

Age: 30
Gender: male


In [44]:
ban = Person()

In [45]:
ban.print_stats()

Age: 20
Gender: male


In [46]:
dan.print_stats()

Age: 30
Gender: male


In [50]:
class Band(object):
    def __init__(self):
        self.band_name = 'Queen'
        self.no_of_member = 4
        self.no_of_albums = 15
        self.no_of_records = 105000000
        self.band_genre = 'Rock'

    def print_stats(self):
        print("Band: ",self.band_name)
        print("Members: ", self.no_of_member)
        print("Albums: ", self.no_of_albums)
        print("Sold: ", self.no_of_records)
        print("Genre: ",self.band_genre)

Queen = Band()
print(Queen.print_stats())

Band:  Queen
Members:  4
Albums:  15
Sold:  105000000
Genre:  Rock
None


In [60]:
class Band(object):
    def __init__(self,band='queen',member=4,albums=15,records=105000000,genre='rock'):
        self.band_name = band
        self.no_of_member = member
        self.no_of_albums = albums
        self.no_of_records = records
        self.band_genre = genre

    def print_stats(self):
        return "band: {} members: {} albumbs: {} Sold: {} genre: {}". format(self.band_name,self.no_of_member,self.no_of_albums,self.no_of_records,self.band_genre)
        

Queen = Band()
print(Queen.print_stats())

band: queen members: 4 albumbs: 15 Sold: 105000000 genre: rock


In [61]:
hello

NameError: name 'hello' is not defined

In [62]:
str_to_float = ['2.3','2.5','$120.3','2,3','5.2%']

floats = []
bad_chars = ',$%'
for s in str_to_float:
    corrupted = False
    for bc in bad_chars:
        if bc in s:
            corrupted = True
    if corrupted:
        floats.append(None)
    else:
        floats.append(float(s))

In [63]:
floats

[2.3, 2.5, None, None, None]

In [66]:
str_to_float = ['2.3','2.5','$120.3','2,3','5.2%','A.A','Five.six','2.3']

floats = []
for s in str_to_float:
    try:
        floats.append(float(s))
    except:
        floats.append(None)

In [67]:
floats

[2.3, 2.5, None, None, None, None, None, 2.3]

In [79]:
def adder(x, y):
    try:
        z = x+y
    except TypeError as target:
        print ('cannot add these types together')
    else:
        print('result is:', str(z))
    finally:
        print('print anyway')

In [80]:
adder('V','A')

result is: VA
print anyway


In [81]:
def no_four(number):
    if number == 4:
        raise ValueError('No fours allowed!!')
    else:
        print('Number:', number)

In [83]:
no_four(4)

ValueError: No fours allowed!!

In [88]:
import numpy as np



In [90]:
mean = 0

std = 10

series_length = 20

normal_series = np.random.normal(mean, std, series_length)

print (normal_series)

[  6.39672354   6.56128033  -0.36505682   2.85622997   5.93944853
   3.97127373  -2.20750969   7.70841365  -1.0407616   -8.17315822
  12.91565409 -15.33961574   5.26300184 -12.24507594   6.31797686
   8.2085901   -0.16852197  10.41097288  -1.93657301  -2.79099343]


In [91]:
np.random.rand(3,1)

array([[0.10258136],
       [0.91509345],
       [0.06577   ]])

In [95]:
print(np.random.rand(3,1))

[[0.02511742]
 [0.78971029]
 [0.24203204]]


In [96]:
my_array = np.array([[2,1],[7,4],[5,2],[6,3]])

print(my_array)

my_array.shape

[[2 1]
 [7 4]
 [5 2]
 [6 3]]


(4, 2)

In [5]:
from scipy import stats

In [6]:
sample = [1033, 75, 98, 20, 10, 3, 14, 98, 44, 25, 31, 100, 356, 4, 23, 55, 327, 98, 6, 20]

mean = np.mean(sample)

median = np.median(sample)

print("mean / median:", mean, median)

mean / median: 122.0 37.5


In [7]:
mode = stats.mode(sample)

In [108]:
print(mode.mode,mode.count)

[98] [3]


In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(np.array([[.25,10,600,'Apple'], [-.9,40,200,'Mango'], [.4,70,800,'Pinapple'], [.8,50,300,'Bananna']]), columns=["A","B","C","D"])
print (df)

      A   B    C         D
0  0.25  10  600     Apple
1  -0.9  40  200     Mango
2   0.4  70  800  Pinapple
3   0.8  50  300   Bananna


In [112]:
df[["A","C"]]

A      C
0  0.25  600.0
1 -0.90  200.0
2  0.40  800.0
3  0.80  300.0

In [113]:
df.A

0    0.25
1   -0.90
2    0.40
3    0.80
Name: A, dtype: float64

In [114]:
df[["A"]]

A
0  0.25
1 -0.90
2  0.40
3  0.80

In [118]:
df[1:2]

A     B      C
1 -0.9  40.0  200.0

In [119]:
df[0:3]

A     B      C
0  0.25  10.0  600.0
1 -0.90  40.0  200.0
2  0.40  70.0  800.0

In [120]:
df[0:0]

Empty DataFrame
Columns: [A, B, C]
Index: []

In [121]:
df

A     B      C
0  0.25  10.0  600.0
1 -0.90  40.0  200.0
2  0.40  70.0  800.0
3  0.80  50.0  300.0

In [131]:
df.iloc[1]

A     -0.9
B       40
C      200
D    Mango
Name: 1, dtype: object

In [129]:
df.iloc[2]

A         0.4
B          70
C         800
D    Pinapple
Name: 2, dtype: object

In [130]:
df.iloc[3]

A        0.8
B         50
C        300
D    Bananna
Name: 3, dtype: object

In [128]:
df.iloc[3]

A        0.8
B         50
C        300
D    Bananna
Name: 3, dtype: object

In [12]:
df['A']>0

0     True
1    False
2     True
3     True
Name: A, dtype: bool

In [11]:
df = pd.DataFrame(np.array([[.25,10,600], [-.9,40,200], [.4,40,800], [.8,50,300]]), columns=["A","B","C"])

In [135]:
df['A']>0

0     True
1    False
2     True
3     True
Name: A, dtype: bool

In [136]:
df['A']

0    0.25
1   -0.90
2    0.40
3    0.80
Name: A, dtype: float64

In [137]:
df[df['A']>0]

A     B      C
0  0.25  10.0  600.0
2  0.40  70.0  800.0
3  0.80  50.0  300.0

In [138]:
df

A     B      C
0  0.25  10.0  600.0
1 -0.90  40.0  200.0
2  0.40  70.0  800.0
3  0.80  50.0  300.0

In [141]:
df[df['B']== 40]

A     B      C
1 -0.9  40.0  200.0
2  0.4  40.0  800.0

In [142]:
df

A     B      C
0  0.25  10.0  600.0
1 -0.90  40.0  200.0
2  0.40  40.0  800.0
3  0.80  50.0  300.0

In [150]:
df.iloc[1:3,0:3]

A     B      C
1 -0.9  40.0  200.0
2  0.4  40.0  800.0

In [154]:
df["D"]=["Apple","Mango","Pineapple","Bananna"]

In [152]:
df

A     B      C          D
0  0.25  10.0  600.0      Apple
1 -0.90  40.0  200.0      Mango
2  0.40  40.0  800.0  Pineapple
3  0.80  50.0  300.0    Bananna

In [155]:
df


A     B      C          D
0  0.25  10.0  600.0      Apple
1 -0.90  40.0  200.0      Mango
2  0.40  40.0  800.0  Pineapple
3  0.80  50.0  300.0    Bananna

In [1]:
df = pd.DataFrame({'A':['A', 'B', 'C'], 'B':[4, 5, 6]})

group_df = df.groupby('A').mean()

type(group_df)

NameError: name 'pd' is not defined

In [2]:
x = [1,2,3,4,5]
y = [6,5,4,3,2]

import numpy as np

print(np.cov(x,y) )           ## Prints the covariance matrix.
print(np.corrcoef(x,y))   ## Prints the correlation matrix.

[[ 2.5 -2.5]
 [-2.5  2.5]]
[[ 1. -1.]
 [-1.  1.]]
